# Generated by Django 2.2.5 on 2019-09-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('u', 'user'), ('l', 'lessor'), ('e', 'service')], max_length=10)),
                ('user_address', models.TextField(blank=True, max_length=140)),
                ('user_phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service_description', models.TextField()),
                ('service_price', models.IntegerField(default=0)),
                ('service_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('place_address', models.TextField()),
                ('place_description', models.TextField()),
                ('place_price', models.IntegerField(default=0)),
                ('place_owner', models.ForeignKey(default='UserDetail.username where UserDetail.user_type==2', on_delete=django.db.models.deletion.CASCADE, to='event.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='MicroBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=20)),
                ('blog_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Place')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.UserDetail')),
            ],
        ),
    ]
