# Generated by Django 2.2.5 on 2019-09-29 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='userinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.UserDetail'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(choices=[('u', 'user'), ('l', 'lessor'), ('e', 'service')], default='u', max_length=10),
        ),
    ]
