# Generated by Django 2.2.5 on 2019-10-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190929_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_address',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
