# Generated by Django 2.2.5 on 2019-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191001_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
