# Generated by Django 2.2.5 on 2019-10-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191001_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_address',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
