# Generated by Django 2.2.5 on 2019-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191001_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_address',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_phone',
            field=models.CharField(max_length=13),
        ),
    ]
