# Generated by Django 2.2.5 on 2019-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20191001_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_address',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
