# Generated by Django 2.2.5 on 2019-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20191001_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_address',
            field=models.TextField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
