# Generated by Django 2.2.5 on 2019-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20191004_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'lessor'), (3, 'service')], max_length=10),
        ),
    ]
