# Generated by Django 2.2.5 on 2019-10-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20191005_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects-images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_owner',
            field=models.ForeignKey(limit_choices_to={'user_type': '3'}, on_delete=django.db.models.deletion.CASCADE, to='event.UserDetail'),
        ),
    ]
