# Generated by Django 2.2.5 on 2019-11-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20191010_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
